export const styles = StyleSheet.create({
    backgroundImage: {
        flex: 1,
        width: "100%",
        height: "100%",
    },
    gradient: {
        flex: 1,
        width: "100%",
    },
    mainContainer: {
        flex: 1,
    },
    container: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#00000040",
    }, 
    div2: {
        justifyContent: "center",
        alignItems: "center",
        gap: 20,
        width: "100%",
    },
    area: {
        backgroundColor: "white",   
        width: "85%",
        maxWidth: 320,
        padding: 20,    
        borderRadius: 16,
        justifyContent: "center",
        gap: 10,
        elevation: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    tituloForm: {
        color: "black",   
        fontWeight: "bold",
        fontSize: 22,
        alignSelf: "center",
        marginBottom: 5,
    },
    subtitulo: {
        color: "#666",
        fontSize: 13,
        textAlign: "center",
        marginBottom: 10,
    },
    textdisplay: {
        backgroundColor: "#77777715",  
        borderRadius: 8,
        padding: 10,
        width: "100%",
        borderWidth: 1,
        borderColor: "#ddd",
    }, 
    textos_register: {
        color: "#333",   
        fontWeight: "600",
        fontSize: 14,
    },
    button: {
        backgroundColor: "#6565b3",   
        width: "85%",
        maxWidth: 320,
        borderRadius: 16,
        paddingVertical: 12,
        justifyContent: "center",
        alignItems: "center",
    }, 
    textButton: {
        color: "white",   
        fontWeight: "bold",
        fontSize: 16,
    },
});